In [7]:
import numpy as np



# Los datos están representados como un array bidimensional de NumPy, donde cada fila es un piloto y cada columna una carrera.
pilotos = np.array([
    [3, 4, 2, 5, 3],  
    [2, 1, 4, 3, 4],  
    [4, 3, 1, 2, 1],  
    [5, 5, 5, 4, 5],  
    [1, 1, 2, 2, 1],  
    [2, 3, 3, 5, 4],  
    [3, 4, 4, 3, 2],  
    [4, 2, 5, 1, 3],  
    [5, 3, 1, 4, 2],
    [1, 1, 1, 1, 1]
])

# Reorganiza la matriz con .reshape() para analizar los datos de otra manera.
pilotos_reshape = pilotos.reshape(5, 10)  
print('Matriz reestructurada:\n', pilotos_reshape)

# Usa .ravel() o .flatten() para convertir la matriz en un array 1D.
pilotos_ravel = pilotos.ravel() 
pilotos_flatten = pilotos.flatten()  
print('Array 1D con .ravel():\n', pilotos_ravel)
print('Array 1D con .flatten():\n', pilotos_flatten)

# calcula el promedio de posiciones por piloto (axis=1) y por carrera (axis=0).
promedio_piloto = np.mean(pilotos, axis=1)  
promedio_carrera = np.mean(pilotos, axis=0)  
print('Promedio de posiciones por piloto:\n', promedio_piloto)
print('Promedio de posiciones por carrera:\n', promedio_carrera)

# Aplica una penalización sumando un valor a cada posición y recalculando los valores.
penalizacion = 2  
pilotos_con_penalizacion = pilotos + penalizacion  
print('Matriz con penalización:\n', pilotos_con_penalizacion)

# Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el producto escalar.
piloto_1 = pilotos[0]  
piloto_2 = pilotos[1] 
producto_escalar = np.dot(piloto_1, piloto_2)  
print('Producto escalar entre Piloto 1 y Piloto 2:', producto_escalar)

# Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D  y calcula su producto cruzado, interpretando el resultado en términos de diferencias de rendimiento.
piloto_1_3d = pilotos[0, :3]  
piloto_2_3d = pilotos[1, :3]  
producto_cruzado = np.cross(piloto_1_3d, piloto_2_3d) 
print('Producto cruzado entre Piloto 1 y Piloto 2 en las primeras 3 carreras:', producto_cruzado)

# Normaliza los datos usando la norma L2 para comparar el rendimiento de los pilotos en diferentes circuitos.
pilotos_normalizados = pilotos / np.linalg.norm(pilotos, axis=1, keepdims=True) 
print('Matriz de pilotos normalizada (norma L2):\n', pilotos_normalizados)


Matriz reestructurada:
 [[3 4 2 5 3 2 1 4 3 4]
 [4 3 1 2 1 5 5 5 4 5]
 [1 1 2 2 1 2 3 3 5 4]
 [3 4 4 3 2 4 2 5 1 3]
 [5 3 1 4 2 1 1 1 1 1]]
Array 1D con .ravel():
 [3 4 2 5 3 2 1 4 3 4 4 3 1 2 1 5 5 5 4 5 1 1 2 2 1 2 3 3 5 4 3 4 4 3 2 4 2
 5 1 3 5 3 1 4 2 1 1 1 1 1]
Array 1D con .flatten():
 [3 4 2 5 3 2 1 4 3 4 4 3 1 2 1 5 5 5 4 5 1 1 2 2 1 2 3 3 5 4 3 4 4 3 2 4 2
 5 1 3 5 3 1 4 2 1 1 1 1 1]
Promedio de posiciones por piloto:
 [3.4 2.8 2.2 4.8 1.4 3.4 3.2 3.  3.  1. ]
Promedio de posiciones por carrera:
 [3.  2.7 2.8 3.  2.6]
Matriz con penalización:
 [[5 6 4 7 5]
 [4 3 6 5 6]
 [6 5 3 4 3]
 [7 7 7 6 7]
 [3 3 4 4 3]
 [4 5 5 7 6]
 [5 6 6 5 4]
 [6 4 7 3 5]
 [7 5 3 6 4]
 [3 3 3 3 3]]
Producto escalar entre Piloto 1 y Piloto 2: 45
Producto cruzado entre Piloto 1 y Piloto 2 en las primeras 3 carreras: [14 -8 -5]
Matriz de pilotos normalizada (norma L2):
 [[0.37796447 0.50395263 0.25197632 0.62994079 0.37796447]
 [0.29488391 0.14744196 0.58976782 0.44232587 0.58976782]
 [0.71842121 0.5388159