# Investigación sobre NumPy

## 1. ¿Qué es NumPy y para qué se utiliza en programación científica?
NumPy (Numerical Python) es una biblioteca  para la programación científica en Python para trabajar con arrays multidimensionales y matricescon una amplia colección de funciones matemáticas y lógicas para operar con los arrays. Se utiliza  para realizar cálculos numéricos de alto rendimiento, como en la simulación de sistemas físicos, procesamiento de imágenes y análisis de datos

## 2. Historia de NumPy
NumPy fue creado por Travis Olliphant en 2005 como una extensión de una librería llamada Numeric. Numeric fue desarrollada a fines de la década de 1990, y NumPy surgió con el propósito de mejorar y ofrecer una solución más robusta para manejar arrays en Python. Con el tiempo, NumPy se ha convertido en una herramienta esencial en la comunidad de ciencia de datos y programación científica.

## 3. ¿Cuál es la diferencia entre una lista de Python y un array de NumPy?
Un array de NumPy contiene elementos del mismo tipo, mientras que una lista en Python puede contener elementos de diferentes tipos.
Los arrays de NumPy permiten realizar operaciones matemáticas de manera eficiente sobre todo el array sin necesidad de bucles explícitos.
Los arrays de NumPy son más eficientes en memoria que las listas de Python, especialmente para grandes volúmenes de datos.


## 4. ¿Cómo se crea un array en NumPy? Explicar y dar ejemplos de:
### Un array unidimensional:
```python
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
```
Salida:
[1 2 3 4 5]

### Un array bidimensional:
```python
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)
```
Salida:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

### Un array de valores inicializados con ceros, unos y valores aleatorios:

- Con ceros:
```python
array_zeros = np.zeros((3, 3))
print(array_zeros)
```
Salida:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
- Con unos:
```python
array_ones = np.ones((2, 4))
print(array_ones)
```
Salida:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Con valores aleatorios:
```python
array_random = np.random.rand(3, 2)
print(array_random)
```
Salida (valores aleatorios entre 0 y 1):
[[0.72939472 0.07869571]
 [0.31904376 0.95175967]
 [0.23605626 0.37735398]]

## 5. ¿Cómo acceder a los elementos de un array y cómo modificar sus valores?
Puedes acceder a los elementos de un array utilizando índices y slicing (corte). Para modificar valore asignas nuevos valores a los índices correspondientes.

```python
array = np.array([10, 20, 30, 40, 50])
print(array[0])  # Acceder al primer elemento
array[2] = 99   # Modificar el tercer elemento
print(array)
```
Salida:
[10 20 99 40 50]

## 6. ¿Qué son los ejes (axis) en un array multidimensional? Explica con ejemplos prácticos.
En un array multidimensional, los ejes son las dimensiones a lo largo de las cuales se realizan las operaciones. En un array 2D, el **axis=0** se refiere a las filas (dirección vertical) y el axis=1 a las columnas (dirección horizontal).
Ejemplo con un array 2D:
```python
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sumar_filas = np.sum(array_2d, axis=0)
sumar_columnas = np.sum(array_2d, axis=1)
print(sumar_filas)  # Suma por columnas (axis=0)
print(sumar_columnas)  # Suma por filas (axis=1)
```
Salida:
Suma por columnas (axis=0): [12 15 18]
Suma por filas (axis=1): [ 6 15 24]

## 7. Explica la diferencia entre np.dot() (producto escalar) y np.cross() (producto cruzado).
El producto escalar entre dos vectores calcula la suma de los productos de sus elementos correspondientes. Es útil para medir la similitud entre dos vectores.
```python
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
producto_escalar = np.dot(v1, v2)
print(producto_escalar)
```
Salida:
32
El producto cruzado entre dos vectores en 3D genera un vector perpendicular a ambos. Se usa en física y geometría.
Ejemplo:
```python
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
producto_cruzado = np.cross(v1, v2)
print(producto_cruzado)
```
Salida:
[-3  6 -3]

## 8. ¿Cómo se pueden transformar las dimensiones de un array? Explica con ejemplos las funciones reshape() y flatten().
 se utiliza para cambiar la forma de un array sin cambiar sus datos.

```python
array = np.array([1, 2, 3, 4, 5, 6])
array_reshape = array.reshape(2, 3)
print(array_reshape)
```
Salida:
[[1 2 3]
 [4 5 6]]
### flatten():
convierte un array multidimensional en un array unidimensional.
```python
array_flat = array_reshape.flatten()
print(array_flat)
```
Salida:
[1 2 3 4 5 6]

## 9. ¿Qué es Matplotlib y en qué situaciones se usa en programación?
Matplotlib es una biblioteca de visualización en Python que se utiliza para crear gráficos estáticos, animados e interactivos. Es ampliamente utilizada en análisis de datos para representar visualmente los resultados de cálculos y simulaciones.
Es especialmente útil en programación científica y en la ciencia de datos, donde la visualización de datos es esencial para interpretar y comunicar los resultados de manera efectiva.
