In [3]:
import numpy as np

#1 crea un array 1D con los números del 1 al 10
array_1d = np.arange(1, 11)
print(array_1d)

# crea un array 2D de tamaño 3x3 con valores del 1 al 9
array_2d = np.arange(1, 10).reshape(3, 3)
print(array_2d)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#2 indexación en arrays
# primer y último elemento del array 1D
print(array_1d[0], array_1d[-1])

# primer elemento de la primera fila del array 2D
print(array_2d[0, 0])

# último elemento de la última fila del array 2D
print(array_2d[-1, -1])

# elemento ubicado en la segunda fila y tercera columna del array 2D
print(array_2d[1, 2])

1 10
1
9
6


In [5]:
#3 selección de filas y columnas
# primera fila completa del array 2D
print(array_2d[0, :])

# segunda columna completa del array 2D
print(array_2d[:, 1])

[1 2 3]
[2 5 8]


In [10]:
#4. Explorando una imagen en formato de Array 3D
#  genera un array 3D de tamaño 4x4x3 con valores aleatorios entre 0 y 255
imagen = np.random.randint(0, 256, (4, 4, 3))
print(imagen)

# indexación en el array 3D
# primer píxel con sus valores RGB
print(imagen[0, 0, :])

# último píxel de la imagen
print(imagen[-1, -1, :])

# valor del canal rojo del píxel en la segunda fila y tercera columna
print(imagen[1, 2, 0])

[[[ 83 151 217]
  [ 34  50   3]
  [129  59 147]
  [ 54  43  50]]

 [[219  77  16]
  [ 47  49  63]
  [122 122 118]
  [224 251  33]]

 [[222 255  50]
  [128 133  91]
  [ 89  50 245]
  [ 43 128  28]]

 [[233  74  25]
  [222 215 161]
  [223 252 108]
  [154  71  84]]]
[ 83 151 217]
[154  71  84]
122


In [7]:
# slicing en el array 3D
# toda la primera fila de la imagen
print(imagen[0, :, :])

# solo los valores del canal azul para todos los píxeles
print(imagen[:, :, 2])

# recorte central de la imagen
print(imagen[1:3, 1:3, :])

[[230 186  12]
 [ 62 243 247]
 [195 135  86]
 [106 243  31]]
[[ 12 247  86  31]
 [102  44 127 252]
 [218 147 155 208]
 [228  60 197 142]]
[[[173 117  44]
  [201 113 127]]

 [[221   6 147]
  [ 19 146 155]]]
