In [2]:
import numpy as np

# Representar el rendimiento de los jugadores como una matriz en NumPy.
jugadores = np.array([
    [10, 7, 300, 25, 40],  
    [15, 10, 250, 30, 50], 
    [5, 12, 280, 20, 35],  
    [8, 6, 310, 15, 38],   
    [12, 9, 270, 28, 45]   
])

# Aplicar la normalización L2 a cada jugador (por filas, usando axis=1).
normas_l2 = np.linalg.norm(jugadores, axis=1, keepdims=True)  # Calcular la norma L2 por jugador
jugadores_normalizados = jugadores / normas_l2  # Dividir cada fila por su norma L2

# Mostrar las estadísticas normalizadas de los jugadores
print("Estadísticas normalizadas de los jugadores:")
print(jugadores_normalizados)

# Pregunta 1: ¿Cómo cambian los valores después de la normalización?
# Respuesta: Los valores de cada jugador se escalan de forma proporcional pero ajustados a una escala donde la suma de los cuadrados de los valores es igual a 1

# Pregunta 2: ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
# Respuesta: La normalización L2 elimina  las diferencias de escala entre las categoríasasi cada estadística contribuye proporcionalmente

# Pregunta 3: ¿Qué pasaría si normalizamos por columnas (axis=0) en lugar de por filas?
# Respuesta: Si normalizamos por columnas hacemmos que las estadísticas sean comparables entre categorías pero perdiendo proporcionalidad


Estadísticas normalizadas de los jugadores:
[[0.03290221 0.02303155 0.98706643 0.08225554 0.13160886]
 [0.05828815 0.03885877 0.97146918 0.1165763  0.19429384]
 [0.01765627 0.04237506 0.98875136 0.0706251  0.12359392]
 [0.02557216 0.01917912 0.9909212  0.0479478  0.12146776]
 [0.04354749 0.03266062 0.97981848 0.10161081 0.16330308]]
