In [2]:
import numpy as np

# 1Crear un array unidimensional con el nombre de los productos
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print(productos)

['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']


In [3]:
# 2Crear un array bidimensional con la cantidad en stock de cada producto
stock = np.array([
    [50, 20, 30],  # stock de smartphone en diferentes almacenes
    [30, 15, 10],  # stock de tablet en diferentes almacenes
    [15, 10, 5],   # stock de laptop en diferentes almacenes
    [40, 25, 35],  # stock de auriculares en diferentes almacenes
    [60, 45, 50]   # stock de teclado en diferentes almacenes
])
print(stock)

[[50 20 30]
 [30 15 10]
 [15 10  5]
 [40 25 35]
 [60 45 50]]


In [4]:
#3 Crear un array tridimensional para registrar las ventas de cada producto durante una semana
ventas = np.array([
    [5, 3, 2, 6, 4],  
    [7, 4, 1, 8, 5],  
    [6, 2, 3, 5, 4]   
])
print(ventas)

[[5 3 2 6 4]
 [7 4 1 8 5]
 [6 2 3 5 4]]


In [5]:
#4 Crear un array de ceros para los productos no vendidos hoy
no_vendidos = np.zeros(5)
print(no_vendidos)

[0. 0. 0. 0. 0.]


In [6]:
#5Crear un array de unos para los productos que están en promoción
promocion = np.array([1, 0, 0, 0, 1])
print(promocion)

[1 0 0 0 1]


In [7]:
#6 Crear un array con un rango de precios de productos
precios_rango = np.arange(50, 1050, 50)
print(precios_rango)

[  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]


In [8]:
#7 Crear un array de precios aleatorios
precios_aleatorios = np.random.uniform(100, 500, 5)
print(precios_aleatorios)

[483.24284798 181.09480526 185.13471182 210.1097336  471.67531952]


In [9]:
#8 Generar un array de números enteros aleatorios para la cantidad vendida
unidades_vendidas = np.random.randint(1, 10, 5)
print(unidades_vendidas)

[2 9 4 1 1]


In [10]:
#9Crear un array vacío para almacenar los valores de descuento
descuentos = np.empty((5, 1))
print(descuentos)

[[483.24284798]
 [181.09480526]
 [185.13471182]
 [210.1097336 ]
 [471.67531952]]


In [11]:
#10 Generar un array con valores espaciados para analizar el cambio en las ventas:
ventas_espaciadas = np.linspace(0, 1000, 5)
print(ventas_espaciadas)

[   0.  250.  500.  750. 1000.]
